language: scala

cache:
  directories:
    - $HOME/.m2

scala:
   - 2.11.4

# Travis has a bug, only oraclejdk8 is a valid keyword https://github.com/travis-ci/travis-ci/issues/1647
jdk:
 - oraclejdk8

script:
   - sbt ++$TRAVIS_SCALA_VERSION test
